resolver: lts-9.21

packages:
- .
# - location:
#     git: git@github.com:SuperpowersCorp/language-javascript-optics.git
#     commit: ba8cbc288b7b1bcfe98d7b7e1ca0b3c9992433b5
#   extra-dep: true
- location: ../language-javascript-optics
  # extra-dep: true

allow-newer: true

extra-deps:
- Cabal-2.0.0.2
- aeson-lens-0.5.0.0
- haskell-src-exts-prisms-1.18.2.0
- hexml-lens-0.2.1
- hexpat-lens-0.1.7
- hexpat-tagsoup-0.1
- hierarchy-0.3.1.4
- io-capture-1.0.0
- lens-4.15.4
- mueval-0.9.3
- number-show-0.1.0.0
- pandoc-lens-0.6.3
- pipes-4.3.9
- pipes-files-0.1.2
- protolude-0.2.1
- show-0.6
- taggy-0.2.1
- taggy-lens-0.1.2
- xml-html-conduit-lens-0.3.2.3
